server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rick-ye/special

security:
  basic:
    enabled: true
  user:
    name: user
    password: password